site_name: TradingInPython
site_description: Documentation officielle de la plateforme TradingInPython
site_author: Bruno Raby
site_url: https://mabyre.github.io/TradingInPython-doc/
use_directory_urls: true

repo_name: TradingInPython
repo_url: https://github.com/SoDevLog/PyTrading/
edit_uri: edit/main/docs/

theme:
  name: material
  language: fr
  palette:
    primary: blue grey
    accent: indigo
  features:
    #- navigation.expand # tout déplié au départ
    - navigation.instant
    #- navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy
    - content.tabs.link
    #- toc.integrate # intègre la table des matières dans la page -> c'est pas joli !!!
    #- toc.follow # fait défiler la table des matières avec le contenu
    #- toc.number # active la numérotation automatique des titres ne fonctionne pas !!!
  icon:
    logo: material/chart-line
    repo: fontawesome/brands/github

extra_javascript:
  - js/glightbox.min.js
  - js/init.js

extra_css:
  - css/glightbox.min.css
  - css/extra.css
  - css/summary.css

nav:
  - Accueil: index.md
  - Tour rapide: tour-rapide.md
  - Récupération des données: recuperation-des-data.md
  - Voyager dans le temps: voyage-dans-le-temps.md
  - Sélectionner une action: select_stock.md
  - Routine de trading: trading-routine.md
  - Stratégies intégrées:
      - Vue d'ensemble: strategies.md
      - Ichimoku & Deep Learning: strategies/ichimoku_kinko_hyo.md
      - Bandes de Bollinger (multiframe): strategies/bollinger.md
      - Oscillateurs & Volumes: strategies/oscillators.md
      - Fractals & Gator: strategies/fractals_gator.md
      - Filtre de Kalman: strategies/kalman.md
      - Prédiction IA (Keras / JAX): strategies/prediction_ai.md
  - Heatmap & Screeners: 
      - Création des Screeners: heatmap-screener/screeners.md
      - Cartes de Chaleurs & Performances: heatmap-screener/heatmaps.md
  - Monitor & Alertes: 
      - Monitorer le marché: monitor-alerts/monitor-stock-market.md
      - Alertes techniques: monitor-alerts/alertes-techniques.md
  - Gestionnaire de Portefeuilles: portfolio_manager.md
  - Interface & Configuration: 
      - Configuration: interface-configuration/ui-configuration.md
      - Gestion automatisée des fenêtres: interface-configuration/windows-management.md
      - Mode sombre: interface-configuration/dark-mode.md
      - Console en bas à droite: interface-configuration/console-bottom-right.md
  - Extensions & Open Software: extension_open.md
  - Notes: 
      - Images: tests/images.md
      - Titres: tests/titres.md 
      - Notes: tests/notes.md 
  - FAQ: faq.md
  - Glossaire: glossary.md

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - tags
  - macros
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: timeago

extra:
  base_url: /TradingInPython-doc   # utiliser {{ base_url }} dans <img src="{{ base_url }}/images/..." 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sodevlog
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bruno-raby
    - icon: fontawesome/brands/webflow
      link: https://www.trading-et-data-analyses.com

copyright: >
  © 2025 <a href="https://www.trading-et-data-analyses.com">Trading et Data Analyses</a> – 
  Propulsé par <a href="https://www.mkdocs.org">MkDocs</a> et <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a>.
