site_name: TradingInPython
site_description: Documentation officielle de la plateforme TradingInPython
site_author: Bruno Raby
site_url: https://mabyre.github.io/TradingInPython-doc/
use_directory_urls: true

repo_name: TradingInPython
repo_url: https://github.com/SoDevLog/PyTrading/
edit_uri: edit/main/docs/

theme:
  name: material
  language: fr
  palette:
    primary: blue grey
    accent: indigo
  features:
    #- navigation.expand # tout déplié au départ
    - navigation.instant
    #- navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy
    - content.tabs.link
    #- toc.integrate # intègre la table des matières dans la page -> c'est pas joli !!!
    #- toc.follow # fait défiler la table des matières avec le contenu
    #- toc.number # active la numérotation automatique des titres ne fonctionne pas !!!
  icon:
    logo: material/chart-line
    repo: fontawesome/brands/github

extra_javascript:
  - js/glightbox.min.js
  - js/init.js

extra_css:
  - css/glightbox.min.css
  - css/extra.css
  - css/summary.css

nav:
  - Accueil: index.md
  - Tour rapide: tour-rapide.md
  - Récupération des données: recuperation-des-data.md
  - Voyager dans le temps: voyage-dans-le-temps.md
  - Gérer la liste des actions: gestion-liste-actions.md
  - Routine de trading: trading-routine.md
  - Stratégies intégrées:
      - Vue d'ensemble: strategies/index.md
      - Ichimoku & Deep Learning: strategies/ichimoku_kinko_hyo.md
      - Moyennes Mobiles: strategies/moyennes-mobiles.md
      - Bandes de Bollinger: strategies/bollinger-bands.md
      - Intraday VWAP + Stoch: strategies/intraday-vwap-stoch.md
      - Analyse Volumique: strategies/analyse-pression-volumique.md
      - Fractales de Bill Williams: strategies/fractales-bill-williams.md
      - Gator Alligator S: strategies/gator-alligator-s.md
      - Filtre de Kalman: strategies/kalman-filter.md
      - Prédiction IA (Keras/Tensorflow/JAX): strategies/prediction_ai.md
  - Heatmap & Screeners: 
      - Création des Screeners: heatmap-screener/screeners.md
      - Cartes de Chaleurs & Performances: heatmap-screener/heatmaps.md
  - Monitor & Alertes: 
      - Monitorer le marché: monitor-alerts/monitor-stock-market.md
      - Alertes techniques: monitor-alerts/alertes-techniques.md
  - Gestionnaire de Portefeuilles: portfolio-manager.md
  - Dessiner sur les Graphes: 
      - Naviguer dans le graphique: draw-on-charts/navigate-on-charts.md
      - Tracer des tendances: draw-on-charts/draw-trend-lines.md
      - Annoter des prix/dates: draw-on-charts/annote-price-date.md
      - Annoter les graphes: draw-on-charts/annotate-charts.md
  - Interface & Configuration: 
      - Configuration: interface-configuration/ui-configuration.md
      - Gestion automatisée des fenêtres: interface-configuration/windows-management.md
      - Mode sombre: interface-configuration/dark-mode.md
      - Console en bas à droite: interface-configuration/console-bottom-right.md
  - Open Software & Logiciel: open-software.md
  - Notes:
      - Images: tests/images.md
      - Titres: tests/titres.md 
      - Notes: tests/notes.md
      - Syntaxe & Links: tests/syntaxe-links.md
      - Glossaire: tests/exemple-glossaire.md
      - Tooltips: tests/tooltips.md
  - Indicateurs Techniques: indicators.md
  - Glossaire: glossaire.md
  - Support & FAQ: support-faq.md

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - tags
  - macros
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: timeago

extra:
  base_url: /TradingInPython-doc   # utiliser {{ base_url }} dans <img src="{{ base_url }}/images/..." 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sodevlog
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bruno-raby
    - icon: fontawesome/brands/webflow
      link: https://www.trading-et-data-analyses.com

copyright: >
  © 2025 <a href="https://www.trading-et-data-analyses.com">Trading et Data Analyses</a> – 
  Propulsé par <a href="https://www.mkdocs.org">MkDocs</a> et <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a>.
